export { default as DataTable } from './DataTable.vue';
export { default as DataTableBody } from './DataTableBody.vue';
export { default as DataTableCell } from './DataTableCell.vue';
export { default as DataTableHeader } from './DataTableHeader.vue';
export { default as DataTableHeading } from './DataTableHeading.vue';
export { default as DataTablePageSelector } from './DataTablePageSelector.vue';
export { default as DataTablePagination } from './DataTablePagination.vue';
export { default as DataTableRow } from './DataTableRow.vue';
export { default as DataTableRowSelector } from './DataTableRowSelector.vue';